 * Serving Flask app 'website'
 * Debug mode: on
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.8/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/azureuser/SpyNet/website/views.py", line 1129, in gedorev2
    with open("website/playlists/gedorev2.txt", 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'website/playlists/gedorev2.txt'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'spy'
Invalid session ezp5FDoBM_rOZYkFAAAQ (further occurrences of this error will be logged with level INFO)
45.79.181.104 - - [05/Apr/2024 07:51:16] code 400, message Bad request version ('À\x14À')
