 * Serving Flask app 'website'
 * Debug mode: on
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'spy'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'spy'
64.62.156.98 - - [12/Apr/2024 11:41:22] code 400, message Bad request version ('À\x14À')
192.155.90.118 - - [12/Apr/2024 11:46:15] code 400, message Bad request version ('À\x14À')
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.8/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 430, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.8/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.8/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 430, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.8/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'spy'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'spy'
Invalid session biJP3JkqjOuHErjKAABG (further occurrences of this error will be logged with level INFO)
185.170.144.3 - - [12/Apr/2024 12:41:30] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'yasminetharwat'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'spy'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'amenaenan'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.8/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 430, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.8/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.8/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/azureuser/SpyNet/website/views.py", line 502, in verifyemail
    return render_template('users_pages/verify.html' , email = user.email , msg = msgg)
AttributeError: 'NoneType' object has no attribute 'email'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/socket.py", line 16, in poll
    packets = [self.queue.get(
  File "/usr/lib/python3.8/queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/socket.py", line 97, in handle_get_request
    packets = self.poll()
  File "/usr/local/lib/python3.8/dist-packages/engineio/socket.py", line 20, in poll
    raise exceptions.QueueEmpty()
engineio.exceptions.QueueEmpty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'hacker'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'spy'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
162.142.125.211 - - [12/Apr/2024 13:42:29] code 505, message Invalid HTTP version (2.0)
162.142.125.211 - - [12/Apr/2024 13:42:32] code 505, message Invalid HTTP version (2.0)
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
