 * Serving Flask app 'website'
 * Debug mode: on
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.8/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 430, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.8/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
205.210.31.11 - - [03/May/2024 01:46:36] code 400, message Bad request version ('À\x13À')
205.210.31.11 - - [03/May/2024 01:46:37] code 400, message Bad request version ('À(À$À\x14À')
20.102.110.198 - - [03/May/2024 02:07:21] code 400, message Bad request version ('RTSP/1.0')
20.102.110.198 - - [03/May/2024 02:07:22] code 400, message Bad HTTP/0.9 request type ('l\x00')
20.102.110.198 - - [03/May/2024 02:11:05] code 400, message Bad request version ('\x00/\x00')
165.22.54.194 - - [03/May/2024 02:42:05] code 400, message Bad request version ('À\x13À')
78.153.140.177 - - [03/May/2024 03:40:29] code 400, message Bad request version ('\x8f´Çg\x00b\x13\x02\x13\x03\x13\x01À,À0À+À/Ì©Ì¨\x00£\x00\x9f\x00¢\x00\x9eÌªÀ¯À\xadÀ$À(À')
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
65.49.20.68 - - [03/May/2024 05:17:58] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03\x8a\x1b=Cð\x99\x91\x8fLÒãb±\x7f\x037\x05\x97Òk=×SB\x84\x07òÑ²Ís÷\x00\x00\x1aÀ/À+À\x11À\x07À\x13À')
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
35.216.167.199 - - [03/May/2024 07:33:14] code 400, message Bad request version ('À\x13À')
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
172.104.11.4 - - [03/May/2024 09:48:07] code 400, message Bad request version ('À\x14À')
Invalid session gje4MEEmnTs9bU0pAABM (further occurrences of this error will be logged with level INFO)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.8/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 430, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.8/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
139.162.251.77 - - [03/May/2024 10:24:43] code 400, message Bad request version ('\x00\x04\x03\x00\x01\x02\x00')
139.162.251.77 - - [03/May/2024 10:24:43] code 400, message Bad request version ('\x00\x04\x03\x00\x01\x02\x00')
139.162.251.77 - - [03/May/2024 10:24:44] code 400, message Bad request version ('\x00\x04\x03\x00\x01\x02\x00')
157.230.37.129 - - [03/May/2024 10:38:57] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x01\x07\x01\x00\x01\x03\x03\x03\x08§Å«Ç!¬»Ð}')
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'alimohamed'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'alhussain'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
45.79.181.251 - - [03/May/2024 14:21:35] code 400, message Bad request version ('À\x14À')
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'manarabdelrahman'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.8/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 430, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.8/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
172.104.11.34 - - [03/May/2024 16:27:25] code 400, message Bad request version ('À\x14À')
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 182, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'spy'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'emad'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 191, in handle_disconnect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'spy'
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'hacker'
172.104.11.4 - - [03/May/2024 18:30:07] code 400, message Bad request version ('À\x14À')
disconnect handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 658, in _handle_eio_disconnect
    self._handle_disconnect(eio_sid, n)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 564, in _handle_disconnect
    self._trigger_event('disconnect', namespace, sid)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 827, in _handle_event
    ret = handler(*args)
  File "/home/azureuser/SpyNet/website/__init__.py", line 192, in handle_disconnect
    connected_usernames.remove(username)  # Remove the username from the set
KeyError: 'spy'
143.198.204.194 - - [03/May/2024 18:36:25] code 400, message Bad request version ('À\x13À')
