 * Serving Flask app 'website'
 * Debug mode: on
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 166, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 823, in _handle_event
    ret = handler(auth)
TypeError: handle_connect() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/engineio/server.py", line 434, in run_handler
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 640, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 534, in _handle_connect
    success = self._trigger_event(
  File "/usr/local/lib/python3.8/dist-packages/socketio/server.py", line 611, in _trigger_event
    return handler(*args)
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "/usr/local/lib/python3.8/dist-packages/flask_socketio/__init__.py", line 825, in _handle_event
    ret = handler()
  File "/home/azureuser/SpyNet/website/__init__.py", line 166, in handle_connect
    username = current_user.username  # Assuming current_user.username is available
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
